version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # - run:
      #     command: pwd && ls -lah
      #     working_directory: ./back-end/back-end

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "./back-end/back-end/pom.xml" }}
          - v1-dependencies-

      - run: cd ./back-end/back-end && mvn dependency:go-offline
      #
      # - save_cache:
      #     paths:
      #       - ~/.m2
      #     key: v1-dependencies-{{ checksum "pom.xml" }}
      #
      # # run tests!
      # - run: mvn integration-test
      #
      # - store_artifacts:
      #     path: ~/repo/target/
